### ISSUE TITLE
funciones de aplicacion movil

### ISSUE THREAD

**Issue by Miguelvillalba** [Miguelvillalba/proyecto_final#24]
se definiran las funciones de la aplicacion movil

**Comment by Miguelvillalba** [comment]
-indetificar el dispositivo del dueño 
-login y formulario de los datos del automovil 
-

**Comment by Gabriel199512** [comment]
como afunciones extras 
- auto guard
- buscador de auto

**Comment by Miguelvillalba** [comment]
-envio automatico en tiempo real de datos del automovil, ubicacion
