### ISSUE TITLE
porcentaje de robo de autos y la razon porque lo hacen.

### ISSUE THREAD

**Issue by Gabriel199512** [Miguelvillalba/proyecto_final#3]
**Robo de autos en estado de hidalgo**
Tulancingo casi triplicó la cifra de robos de autos en un año, según los reportes que emitió el Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública (SESNSP), basados en denuncias ante el Ministerio Público.

De acuerdo con la dependencia nacional, durante 2017 ocurrieron 868 registros de hurtos de vehículos con o sin violencia, a diferencia de 2016, cuando se reportaron 301 casos. Lo que representó un aumento de 567 sustracciones en un año.

En 2017 se presentaron 154 acusaciones de robo de automotor que se cometieron amenazando al conductor (con violencia), mientras que 714 fueron llevados cuando los carros estaban estacionados.
En la demarcación las estadísticas del secretariado reflejan un incremento exponencial en la incidencia mensual de este tipo de crimen.

Durante enero de 2016 se registraron 21 casos, mientras que al corte del mismo mes en 2017, el número aumentó a 74 expedientes.

La tendencia de incremento ha sido constante a partir de marzo de 2017, pues desde entonces la recurrencia no ha bajado de más de 50 casos cada treintena.
En mayo la tasa alcanzó los 87 hurtos, mientras que en agosto 86, los meses con las cifras más altas, según el SESNSP.

Conforme a los datos de la dependencia federal, en Tulancingo se roban, en promedio, dos vehículos al día.

   **Robo de autos en Mexico** 

La Asociación Mexicana de Instituciones de Seguros (AMIS) reveló que en el 2017 se robaron la 'cifra histórica' de 90 mil 187 vehículos asegurados, lo que representó un incremento de 27.2 por ciento con respecto al 2016, cuando alcanzó 70 mil 925 unidades.

De acuerdo con Recaredo Arias, director general de la AMIS, la tendencia al alza del robo de vehículos comenzó en junio de 2015 y desde esa fecha no ha cedido el robo de vehículos asegurados, a tal grado que las cifras alcanzadas en el 2017 son históricas desde que comenzaron a llevarse los registros en 1995.

Durante la presentación de las cifras de "Robo y recuperación de automóviles asegurados al cierre de 2017", el directivo de la AMIS precisó que de los casi 90 mil 200 vehículos asegurados robados el año pasado, el 62 por ciento de ellos fue con violencia, principalmente en los estados de Guerrero, Sinaloa, Estado de México, Tlaxcala y Puebla Cifras de la AMIS destacan que el robo con violencia de vehículos asegurados a nivel nacional durante el 2017 registró el porcentaje más elevado de los últimos años.

Según la AMIS, el pago de indemnización de las aseguradoras por esta cantidad de robo de vehículos será por unos 14 mil 430 millones de pesos, cerca de un 14 por ciento del total del estimado de indemnizaciones que desembolsaran las aseguradoras por 62 mil 12 millones de pesos en este tipo de coberturas.

Las entidades en las que más se dio el robo de vehículos fueron el Estado de México, Jalisco, Ciudad de México, Chihuahua, Sinaloa, Guanajuato.

Hace cinco años, la cifra de autos robados asegurados llegaba a las 68 mil 815 unidades, tres años después de eso, la cifra se fue a más de 70 mil.

Arias sostuvo que los altos índices de delincuencia en México están íntimamente relacionados con el incremento del robo de vehículos, toda vez que prevé que la tendencia de esta práctica delictiva seguirá al alza, en un entorno de elecciones presidenciales este 2018, debido a que se flexibilizan aún más las políticas y no se le da continuidad a los programas de seguridad, ya que algunos funcionarios dejan su cargo para contender a un puesto publico.

De acuerdo con la lista de vehículos por marca y modelo más robados en el 2017, el Tsuru,  la Pick Up y el Versa, todos de Nissansigue siendo el campeón. Le siguen Aveo de General Motors; Sentra de Nissan y Jetta Clásico, de Volkswagen.

 **¿Razones porque roban los autos?**
1. Para desmantelarlos e ingresarlos al mercado de autopartes.
2. Ser llevados a países vecinos para ser matriculados.
3. Solicitar el pago de rescate por el vehículo, configurándose en un secuestro extorsivo además del hurto del vehículo.
4. Darle movilidad a los generadores de violencia como el secuestro, la extorsión, el narcotráfico y la trata de personas.

 **Cómo evitar el robo y cómo recuperarlos**

Ante estas acciones delincuenciales existen diferentes formas de proteger los vehículos para no ser la siguiente víctima de robo, la más básica es tener precaución y evitar descuidos con los vehículos al estacionar o recorrer zonas potencialmente peligrosas.

Pero hay alternativas confiables, tecnológicas y efectivas como la instalación de un sistema especializado de recuperación de vehículos robados que funciona con tecnología de “Radiofrecuencia” aún en túneles, subterráneos y lugares de difícil acceso e incluso debajo del agua. 
 
Referencias:  
https://www.criteriohidalgo.com/regiones/casi-se-triplica-robo-de-autos-con-violencia-en-cuatro-anos

http://www.elfinanciero.com.mx/economia/en-2017-se-robaron-mas-autos-que-nunca-antes

http://www.elsalvador.com/sin-categoria/317896/cuatro-razones-por-las-que-se-roban-los-vehiculos/

**Comment by Miguelvillalba** [comment]
cierre de investigacion
